$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$docsRoot = Join-Path $repoRoot "docs\_local-library-docs"
$reposRoot = Join-Path $docsRoot "repos"
$localManifestPath = Join-Path $repoRoot "AI-LOCAL-LIBRARY-DOCS.local.json5"

$sources = @(
    @{
        Id = "phobos"
        Repo = "dlang/phobos"
        Target = Join-Path $reposRoot "phobos"
        Purpose = "D standard library source and doc comments"
        DocsHint = "Search std/*.d for symbols like std.logger."
    },
    @{
        Id = "dlangui"
        Repo = "dlang-supplemental/dlangui"
        Target = Join-Path $reposRoot "dlangui"
        Purpose = "UI framework used by DevCentr"
        DocsHint = "Search README, examples, views, and src/ for real APIs."
    },
    @{
        Id = "sdlang-d"
        Repo = "dlang-community/SDLang-D"
        Target = Join-Path $reposRoot "SDLang-D"
        Purpose = "SDL parser used by DevCentr"
        DocsHint = "Search README, docs, and src/sdlang/ for parser behavior."
    }
)

New-Item -ItemType Directory -Force -Path $reposRoot | Out-Null

foreach ($source in $sources) {
    $parent = Split-Path -Parent $source.Target
    New-Item -ItemType Directory -Force -Path $parent | Out-Null

    if (Test-Path (Join-Path $source.Target ".git")) {
        Write-Host "Updating $($source.Repo) -> $($source.Target)"
        git -C $source.Target fetch --all --tags --prune
        git -C $source.Target pull --ff-only
    }
    else {
        Write-Host "Cloning $($source.Repo) -> $($source.Target)"
        gh repo clone $source.Repo $source.Target
    }
}

$manifestLines = @(
    "{",
    "  // Generated by scripts/refresh-local-library-docs.ps1",
    "  // AI agents should prefer these local docs over stale model memory.",
    "  strategy: {",
    "    primary: ""repo-local-cloned-docs"",",
    "    fallback: ""web-search"",",
    "  },",
    "",
    "  libraries: ["
)

for ($i = 0; $i -lt $sources.Count; $i++) {
    $source = $sources[$i]
    $comma = if ($i -lt $sources.Count - 1) { "," } else { "" }
    $relativeTarget = $source.Target.Substring($repoRoot.Length).TrimStart("\").Replace("\", "/")
    $manifestLines += @(
        "    {",
        "      id: ""$($source.Id)"",",
        "      purpose: ""$($source.Purpose)"",",
        "      localPath: ""$relativeTarget"",",
        "      docsHint: ""$($source.DocsHint)"",",
        "      upstream: ""https://github.com/$($source.Repo)"",",
        "    }$comma"
    )
}

$manifestLines += @(
    "  ],",
    "}"
)

Set-Content -Path $localManifestPath -Value $manifestLines -Encoding utf8
Write-Host "Wrote $localManifestPath"
